### ISSUE TITLE
Embed data from identified sources into the vector store

### ISSUE THREAD

**Issue by AGI-CEO** [LangLabsIO/longevity-rag#2]

**Comment by shacharbard** [comment]
transcripts from 2 YT channels are ready for embedding.
1. David Sinclair's YT channel (9 transcripts)
2. Reverse Aging Revolution YT channel (382 transcripts)

**Comment by AndrewKPascual** [comment]
https://github.com/LangLabsIO/Longevity-data-retrevial.git

Added lamaindex

**Comment by shacharbard** [comment]
created 2 Supabase collections that include embeddings of 2 YT channels' transcripts.
