### ISSUE TITLE
Andrew create LabLab team for LangLabs

### ISSUE THREAD

**Issue by shacharbard** [LangLabsIO/longevity-rag#3]

**Comment by shacharbard** [comment]
request was sent.

**Comment by AndrewKPascual** [comment]
![Image](https://github.com/LangLabsIO/longevity-rag/assets/95746939/46aa33c0-986d-4d09-8c96-e533179ec4cf)

**Comment by AndrewKPascual** [comment]
https://lablab.ai/event/gemini-ai-hackathon/langlabs?join=clqcg2qfp000r356v1neb7r6h&channel=url @shacharbard
